Repository belastingdienst/opr-paas, pull requests merged in 2024-09, with the labels that each got.

#45 e2e tests for paasns
  test/e2e/paasns_test.go
Labels: enhancement

#38 Add e2e test for capability: sso
  test/e2e/capability-sso_test.go
  test/e2e/main_test.go
  test/e2e/util.go
Labels: enhancement

#46 Define e2e test for groups with queries
  test/e2e/groupquery_test.go
Labels: enhancement

#48 chore: migrate to Material for MKDocs
  .github/workflows/documentation.yaml
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  contribute/README.md
  docs/about/code-of-conduct.md
  docs/about/contributing.md
  docs/about/license.md
  docs/administrators-guide/security.md
  docs/development-guide/20_issues.md
  docs/development-guide/21_security-issues.md
  docs/development-guide/30_submitting-a-pr.md
  docs/development-guide/31_writing-good-pull-request.md
  docs/development-guide/40_e2e-tests.md
  docs/development-guide/50_notes.md
  docs/development-guide/index.md
  docs/index.md
  docs/overview/core_concepts/authorization.md
  docs/overview/core_concepts/caas-whitelist.md
  docs/overview/core_concepts/capabilities.md
  docs/overview/core_concepts/integrations.md
  docs/overview/core_concepts/paas.md
  docs/overview/core_concepts/paasns.md
  docs/overview/core_concepts/sshsecrets.md
  docs/overview/glossary.md
  docs/overview/index.md
  docs/user-guide/01_basic-usage.md
  docs/user-guide/02_adding-extras.md
  mkdocs.yml
Labels: documentation, chore

#50 Creating a release
  .github/release-drafter.yml
Labels: minor

#51 only run code tests when code changes
  .github/workflows/ci-build.yaml
  .github/workflows/codeql.yaml
Labels: infrastructure

#53 Switching back to default codeQL
  .github/workflows/codeql.yaml
Labels: bug

#52 Release action v2
  .github/release-drafter.yml
  .github/workflows/codeql.yaml
  .github/workflows/release.yml
Labels: enhancement

#57 chore: add requirements.txt for documentation publication workflow
  .github/workflows/documentation.yaml
  requirements.txt
Labels: chore

#59 chore: add missing deps
  .github/workflows/documentation.yaml
  requirements.txt
Labels: chore

#55 Compiling binaries and adding to github release
  .github/workflows/binaries.yml
  .gitignore
  .goreleaser.yaml
Labels: enhancement

#56 building image and pushing to ghcr.io for every release
  .github/workflows/images.yml
  Dockerfile
Labels: enhancement

#64 ci: adjust autolabeler config for release drafter
  .github/release-drafter.yml
Labels: ci

#66 ci: improved regexp for autolabeler
  .github/release-drafter.yml
Labels: ci

#65 ci: fixing building images
  Dockerfile
Labels: ci

#67 ci: Adding permissions for images and binaries
  .github/workflows/binaries.yml
  .github/workflows/images.yml
Labels: ci

#68 ci: removing strategy (goreleaser buids all in one step)
  .github/workflows/binaries.yml
Labels: ci

#69 ci: Fixing pushing images / multibuild
  .github/workflows/images.yml
Labels: ci

#70 ci: Change name of binary to crypttool
  .goreleaser.yaml
Labels: ci

#72 ci: Change name of tar to crypttool.*
  .goreleaser.yaml
Labels: ci

#73 ci: Change name of tar to crypttool.*
  .goreleaser.yaml
Labels: ci

#74 ci: Adding webservice image
  .github/workflows/images.yml
  Dockerfile.webservice
Labels: ci

#75 Fixing go build commands in Dockerfiles
  Dockerfile
  Dockerfile.webservice
Labels: ci

#76 ci: Adding SBOM to release
  .github/workflows/images.yml
  .github/workflows/sbom.yml
  .goreleaser.yaml
Labels: ci

#77 ci!: fixing some sbom issues
  .github/workflows/images.yml
  .github/workflows/release.yml
  .github/workflows/sbom.yml
Labels: ci, breaking

#78 ci: release write permissions
  .github/workflows/binaries.yml
  .github/workflows/images.yml
  .github/workflows/release.yml
Labels: ci

#80 ci: release permissions for webservice image (#79)
  .github/workflows/images.yml
  .github/workflows/sbom.yml
  .goreleaser.yaml
Labels: ci
