Repository belastingdienst/opr-paas, pull requests merged in 2024-11, with the labels that each got.

#113 fix: rolebinding reconciliation deadlock
  internal/controller/rolebindings_controller.go
Labels: bug

#115 fix: Requeue PaasNs reconciliation on error
  internal/controller/paasns_controller.go
Labels: bug

#120 fix: Webservice logging
  cmd/webservice/main.go
Labels: bug

#122 feat: Allow ArgoCD defaultPolicy to be configured
  internal/config/config.go
  internal/controller/argocd.go
  internal/stubs/argoproj-labs/v1beta1/gitops.go
  internal/stubs/argoproj-labs/v1beta1/zz_generated.deepcopy.go
  test/e2e/capabilityargocd_test.go
  test/e2e/fixtures/paas_config.yml
  test/e2e/main_test.go
Labels: enhancement, minor

#123 chore: e2e-test for current implementation of secret reconciliation
  Makefile
  test/e2e/sshsecrets_test.go
Labels: chore

#125 feat: Removal of unused secrets!
  internal/controller/secret_controller.go
  test/e2e/sshsecrets_test.go
Labels: enhancement, minor

#126 fix: Setting correct Paas Version in built images
  Dockerfile
  Dockerfile.webservice
  cmd/crypttool/main.go
  cmd/manager/main.go
  cmd/webservice/main.go
  cmd/webservice/main_test.go
  internal/version/main.go
Labels: bug

#129 chore: Remove install.yaml from code
  .github/workflows/ci-run-on-pr.yaml
  Makefile
  hack/update-manifests.sh
  manifests/default/kustomization.yaml
  manifests/kustomization.yaml
  manifests/manager/kustomization.yaml
  manifests/manager/opr-paas-deployment.yaml
Labels: chore, ci

#130 fix: ArgoCD patch permissions
  internal/controller/paas_controller.go
  manifests/rbac/role.yaml
Labels: bug, ci

#131 chore: Generate appropriate permissions
  docs/administrators-guide/install.md
  internal/controller/paas_controller.go
  manifests/rbac/role.yaml
Labels: documentation, chore

#133 chore: Log status in e2e-test wait failures
  test/e2e/paas.go
  test/e2e/paasns.go
Labels: chore

#128 chore: test e2e against built image
  .github/workflows/ci-run-on-pr.yaml
  manifests/config/cm_opr-paas.yaml
  manifests/config/example-keys.yaml
  manifests/config/kustomization.yaml
  manifests/manager/namespace.yaml
  manifests/manager/opr-paas-deployment.yaml
  manifests/rbac/leader_election_role_binding.yaml
  manifests/rbac/role_binding.yaml
  manifests/rbac/service_account.yaml
  test/e2e/fixtures/paas_config.yml
Labels: documentation, chore, ci

#135 chore: upload e2e test logs on failure
  .github/workflows/ci-run-on-pr.yaml
  Makefile
  manifests/default/kustomization.yaml
Labels: chore, ci

#137 chore: Add coverage to e2e-tests
  .github/workflows/ci-run-on-pr.yaml
  Makefile
  Procfile
Labels: chore, ci

#140 feat: PR title check
  .github/pr-title-checker-config.json
  .github/workflows/pr-title-check.yml
Labels: enhancement, ci

#145 fix: Pass errors, related to secrets, to reconciler
  internal/controller/paasns_controller.go
  internal/controller/secret_controller.go
Labels: bug

#151 docs: Don't state that the webservice is deployed via install.yaml
  README.md
  docs/administrators-guide/install.md
Labels: documentation

#152 ci: ReleaseDrafter increment minor version on enhancement
  .github/release-drafter.yml
Labels: ci

#156 docs: Adding docs for e2e tests for configarable capabilities
  docs/development-guide/e2e-test-details.md
Labels: documentation

#159 refactor: PaasNs controller
  internal/controller/paasns_controller.go
Labels: refactor

#157 refactor(controller): replace logging statements with zerolog
  go.mod
  internal/controller/argo_app.go
  internal/controller/argo_projects.go
  internal/controller/argocd.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/main.go
  internal/controller/main_test.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/secret_controller.go
Labels: refactor

#165 chore: remove required from paas.status.quota
  api/v1alpha1/paas_types.go
  manifests/crds/cpet.belastingdienst.nl_paas.yaml
Labels: chore

#166 hotfix: remove less unused secrets
  internal/controller/secret_controller.go
  test/e2e/sshsecrets_test.go
Labels: bug

#167 fix: Set version in built images correctly
  Dockerfile
Labels: bug

#168 fix: Swallow unconfigured capability error
  internal/controller/cluster_quotas.go
Labels: bug

#149 feat: Update resource names to be more opr-paas specific
  .github/workflows/ci-run-on-pr.yaml
  Makefile
  manifests/manager/namespace.yaml
  manifests/manager/opr-paas-deployment.yaml
  manifests/rbac/leader_election_role.yaml
  manifests/rbac/leader_election_role_binding.yaml
  manifests/rbac/role.yaml
  manifests/rbac/role_binding.yaml
  manifests/rbac/service_account.yaml
Labels: enhancement, ci

#172 chore: Finetune paasConfig
  api/v1alpha1/paasconfig_types.go
  docs/administrators-guide/configmap.md
  examples/config/operator-config.yaml
  manifests/config/cm_opr-paas.yaml
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/fixtures/paas_config.yml
  test/manifests/config/paas_config.yml
Labels: documentation, chore

#174 fix: Set version of webservice image correctly
  Dockerfile.webservice
Labels: bug

#175 test(e2e): define tests for capability rolebindings
  docs/development-guide/e2e-test-details.md
  manifests/config/cm_opr-paas.yaml
  test/e2e/capability-tekton_test.go
  test/e2e/capabilityargocd_test.go
  test/e2e/fixtures/paas_config.yml
Labels: documentation, ci
