Repository belastingdienst/opr-paas, pull requests merged in 2024-10, with the labels that each got.

#71 test: argoCD end-to-end test
  .github/workflows/ci-build.yaml
  internal/controller/secret_controller.go
  test/e2e/capability-sso_test.go
  test/e2e/capabilityargocd_test.go
  test/e2e/paasns.go
  test/e2e/steps.go
  test/e2e/util.go
Labels: ci

#83 Adding action for generating install.yaml
  .github/workflows/installyaml.yaml
  README.md
  hack/update-manifests.sh
  manifests/kustomization.yaml
Labels: documentation, ci

#85 installyaml Action fixes
  .github/workflows/installyaml.yaml
Labels: ci

#86 ci: add manual trigger for release drafter
  .github/workflows/release.yml
Labels: ci

#87 ci: add image tag and workflow_dispatch event
  .github/workflows/installyaml.yaml
Labels: ci

#91 ci: cleanup workflows and add install.yaml to release
  .github/workflows/build-and-publish-docs.yaml
  .github/workflows/build-and-release-binaries.yml
  .github/workflows/build-and-release-images.yml
  .github/workflows/build-and-release-installyaml.yaml
  .github/workflows/build-and-release-sbom.yml
  .github/workflows/ci-run-on-pr.yaml
  .github/workflows/draft-release-on-push.yml
  .gitignore
  README.md
  manifests/install.yaml
Labels: documentation, ci

#92 docs: add install.md doc to admin guide
  docs/administrators-guide/install.md
Labels: documentation

#93 ci: regenerate licenses.md on push to main
  .github/workflows/build-and-commit-licensesmd.yaml
Labels: ci

#94 ci: move LICENSES.md out of tree, into release
  .github/workflows/build-and-commit-licensesmd.yaml
  .github/workflows/build-and-release-sbom.yml
  LICENSES.md
  Makefile
  licenses.sh
Labels: documentation, ci

#95 docs: add publiccode.yml to adhere to standard
  publiccode.yml
Labels: documentation

#97 fix(ci): only build licenses.md based on linux/amd64
  .github/workflows/build-and-release-sbom.yml
Labels: bug, ci

#99 fix(ci): revert to latest in manifest
  manifests/kustomization.yaml
Labels: bug

#101 ci: manifests change revert
  manifests/kustomization.yaml
Labels: ci

#100 fix(ci): use correct tag for generated container image
  .github/workflows/build-and-release-images.yml
Labels: bug, ci

#108 fix(ci): correct webservice container image tagging
  .github/workflows/build-and-release-images.yml
Labels: bug, ci

#107 fix: correct management of AppProjects
  internal/controller/argo_projects.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  test/e2e/app-project_test.go
Labels: bug

#109 fix: continue reëncrypt if one fails
  cmd/crypttool/paasFile.go
  cmd/crypttool/reencrypt.go
  cmd/webservice/check_paas_test.go
Labels: bug

#116 chore: update PR template to close related issue
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, chore, ci
