Repository belastingdienst/opr-paas, pull requests merged in 2024-12, with the labels that each got.

#179 chore: Cleanup after implementing configurable capabilities
  api/v1alpha1/paas_types.go
  cmd/crypttool/check_paas.go
  cmd/webservice/check_paas.go
  manifests/crds/cpet.belastingdienst.nl_paas.yaml
Labels: chore

#183 chore: Refactor PaasConfig quota spec
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/groups.go
  internal/quota/quotalists.go
  internal/quota/quotalists_test.go
  internal/quota/quotas.go
  internal/quota/quotas_test.go
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/app-project_test.go
  test/e2e/capability-sso_test.go
  test/e2e/capability-tekton_test.go
  test/e2e/capabilityargocd_test.go
  test/e2e/clusterresourcequota_test.go
  test/e2e/groupquery_test.go
  test/e2e/groupusers_test.go
  test/e2e/paasns_test.go
  test/e2e/sshsecrets_test.go
Labels: chore

#186 chore: Adds regression test for #185
  test/e2e/capabilityargocd_test.go
Labels: chore

#189 chore: update API doc page
  docs/development-guide/00_api.md
Labels: documentation, chore

#154 feat: Use status Conditions for PaasNs
  api/v1alpha1/paasns_types.go
  api/v1alpha1/paasns_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/argo_app.go
  internal/controller/argocd.go
  internal/controller/capabilities.go
  internal/controller/namespaces.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/secret_controller.go
  manifests/crds/cpet.belastingdienst.nl_paasns.yaml
  test/e2e/capability-tekton_test.go
  test/e2e/capabilityargocd_test.go
  test/e2e/paasns.go
  test/e2e/paasns_test.go
  test/e2e/sshsecrets_test.go
Labels: enhancement

#191 feat: Use status conditions for Paas
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasns_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/argo_projects.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/paas_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  manifests/crds/cpet.belastingdienst.nl_paas.yaml
  test/e2e/paas.go
Labels: enhancement

#194 fix: Set release version in crypttool
  .goreleaser.yaml
Labels: bug

#195 feat: Use exponential backoff on reconcile err
  internal/controller/paas_controller.go
  internal/controller/paasns_controller.go
Labels: enhancement

#196 feat: Removes quota from Paas Status
  api/v1alpha1/paas_types.go
  internal/controller/cluster_quotas.go
  manifests/crds/cpet.belastingdienst.nl_paas.yaml
Labels: enhancement

#201 feat: Watch PaasConfig and trigger reconcile on Paas and PaasNS
  api/v1alpha1/paasconfig_types.go
  internal/controller/paas_controller.go
  internal/controller/paasns_controller.go
Labels: enhancement

#203 fix(ci): Ensure we actually install crd-ref-docs
  .github/workflows/build-and-publish-docs.yaml
Labels: bug, ci

#178 feat: Adding options to make capability fields customizable
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/administrators-guide/configuration.md
  docs/development-guide/00_api.md
  internal/controller/argo_app.go
  internal/controller/capabilities.go
  manifests/crds/cpet.belastingdienst.nl_paas.yaml
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/capabilityargocd_test.go
  test/e2e/main_test.go
Labels: documentation, enhancement

#192 ci: Adding e2e-tests for extra capabilities
  internal/controller/cluster_wide_quota.go
  internal/controller/paas_controller.go
  test/e2e/capability-cap5_test.go
  test/e2e/capability-cap6_test.go
  test/e2e/main_test.go
  test/e2e/manifests/paas-context/capability-applicationsets/appset-cap5as.yaml
  test/e2e/manifests/paas-context/capability-applicationsets/kustomization.yaml
  test/e2e/paas.go
  test/e2e/paasns_test.go
  test/e2e/steps.go
  test/e2e/util.go
Labels: ci

#212 docs: a proper description of capabilities
  docs/administrators-guide/capabilities.md
  docs/overview/core_concepts/authorization.md
Labels: documentation

#214 chore: Paas in method definition while not used in body
  internal/controller/clusterrolebindings.go
Labels: chore
