Repository belastingdienst/opr-paas, pull requests merged in 2025-05, with the labels that each got.

#557 ci: improving coverage on internal/controller/namespace_def.go
  .testcoverage.yaml
  internal/controller/clusterrolebindings_test.go
  internal/controller/namespace_def.go
  internal/controller/namespace_def_test.go
Labels: documentation, ci

#566 fix: V1Encrypt webservice returning OK json
  cmd/webservice/main.go
  cmd/webservice/main_test.go
Labels: bug

#564 fix: Config reload mechanism
  .testcoverage.yaml
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasconfig_types_test.go
  cmd/manager/main.go
  internal/config/informer.go
  internal/config/informer_test.go
  internal/config/paas_config_store_test.go
  internal/config/watcher.go
  internal/controller/paasconfig_controller.go
  internal/logging/main.go
Labels: bug

#569 fix: Clusterwide quota calculation
  internal/controller/cluster_wide_quota.go
Labels: bug

#567 test: add coverage for capabilities
  .testcoverage.yaml
  internal/controller/capabilities_test.go
Labels: test

#571 chore: Adds shadowing linter
  .golangci.yaml
  cmd/manager/main.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/paasns_controller.go
  internal/fields/elements_test.go
  test/e2e/sshsecrets_test.go
Labels: chore

#574 chore: moving all controller unittest funcs to suite_test.go
  internal/controller/paas_controller_test.go
  internal/controller/suite_test.go
Labels: chore

#582 chore: unexporting getSchema
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
Labels: chore

#580 chore: Defining assureAppSet
  internal/controller/capabilities_test.go
  internal/controller/suite_test.go
Labels: chore

#581 chore: rebase v1alpha1 on main
  .golangci.yaml
  cmd/manager/main.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/suite_test.go
  internal/fields/elements_test.go
  internal/webhook/v1alpha1/paasns_webhook.go
  test/e2e/sshsecrets_test.go
Labels: documentation, chore

#573 chore: moving all controller unittest funcs to suite_test.go
  internal/controller/namespace_def_test.go
  internal/controller/suite_test.go
Labels: chore

#583 chore: upstream
  .github/workflows/build-and-release-images.yml
  go.mod
  go.sum
  internal/controller/capabilities_test.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/rolebindings_controller.go
  internal/controller/suite_test.go
Labels: chore, ci

#572 chore: Improve label selector to make methods less expensive
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/secret_controller.go
  test/e2e/groupquery_test.go
  test/e2e/groupusers_test.go
Labels: chore

#560 ci: Improving of coverage on paas_controller
  .testcoverage.yaml
  api/v1alpha1/paas_types.go
  internal/controller/main.go
  internal/controller/namespace_def_test.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/rolebindings_controller.go
  internal/controller/suite_test.go
Labels: ci

#585 chore: paas_controller coverage
  .testcoverage.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasns_types.go
  internal/controller/main.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/rolebindings_controller.go
  internal/controller/suite_test.go
  test/e2e/util.go
Labels: chore

#591 chore: Removes redundant finalizers
  .testcoverage.yaml
  internal/controller/cluster_quotas.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
Labels: documentation, chore, ci

#535 ci: Adding api/v1alpha2/paasns_types_test
  api/v1alpha2/paasns_types.go
Labels: ci

#597 fix: PaasConfig webhooks
  internal/config/informer.go
  internal/config/informer_test.go
  internal/controller/paasconfig_controller.go
  manifests/crd/kustomization.yaml
  manifests/crd/patches/webhook_in_paasconfig.yaml
Labels: bug

#596 fix: Removes predicate in Watched PaasNs, as that predicate is unrelated.
  internal/controller/paas_controller.go
Labels: bug

#594 chore: Adding update tests to paas reconcile unittests
  .testcoverage.yaml
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  internal/controller/capabilities.go
  internal/controller/capabilities_test.go
  internal/controller/cluster_quotas.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
Labels: chore

#593 test(controller): add scenarios to cluster-wide quota logic
  internal/controller/cluster_wide_quota_test.go
Labels: test

#604 docs: Removes reference to ArgoCD cap
  docs/overview/core_concepts/authorization.md
Labels: documentation

#605 feat!: Change group Query management
  api/v1alpha2/paasconfig_conversion.go
  api/v1alpha2/paasconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  docs/overview/core_concepts/authorization.md
  docs/overview/core_concepts/groupsynclist.md
  docs/overview/glossary.md
  docs/user-guide/02_groups-and-users.md
  internal/controller/groups.go
  internal/controller/groups_test.go
  internal/controller/ldap_groups.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/validate/main.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/paasconfig_webhook_test.go
  internal/webhook/v1alpha2/paasconfig_webhook.go
  internal/webhook/v1alpha2/paasconfig_webhook_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  manifests/rbac/role.yaml
  test/e2e/groupquery_test.go
  test/e2e/groupusers_test.go
  test/e2e/main_test.go
  test/e2e/manifests/paas-context/groupsynclist/kustomization.yaml
  test/e2e/manifests/paas-context/groupsynclist/ns-gslns.yaml
  test/e2e/manifests/paas-context/kustomization.yaml
Labels: documentation, enhancement, breaking
