Repository belastingdienst/opr-paas, pull requests merged in 2025-04, with the labels that each got.

#500 feat: Adding all validations of #414
  .testcoverage.yaml
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/validations.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/administrators-guide/validations.md
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/paasconfig_webhook_test.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
Labels: documentation, enhancement

#509 feat(v1alpha2): implement conversion to and from v1alpha1
  .testcoverage.yaml
  PROJECT
  api/v1alpha1/paas_types.go
  api/v1alpha2/paas_conversion.go
  api/v1alpha2/paas_conversion_test.go
  api/v1alpha2/paas_types.go
  examples/resources/_v1alpha2_paas.yaml
  manifests/crd/kustomization.yaml
  manifests/crd/patches/webhook_in_paas.yaml
Labels: enhancement

#511 chore: upgrade golangci-lint
  .github/workflows/ci-run-on-pr.yaml
  .golangci.yaml
  Makefile
Labels: chore, ci

#513 chore: bump controller-runtime and spf13/viper deps
  go.mod
  go.sum
Labels: chore

#512 chore(style): enable revive rule comment-spacings
  .golangci.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasns_types.go
  api/v1alpha1/suite_test.go
  cmd/manager/main.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasns_controller.go
  internal/controller/suite_test.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
Labels: chore

#514 docs: Capability configuration including templating
  docs/administrators-guide/capabilities.md
Labels: documentation

#501 feat: Removes some leftovers of ArgoCD related code
  internal/controller/capabilities_test.go
  internal/controller/paas_controller_test.go
  internal/stubs/argoproj/v1alpha1/application.go
  internal/stubs/argoproj/v1alpha1/applicationset_types.go
  internal/stubs/argoproj/v1alpha1/scheme.go
  internal/stubs/argoproj/v1alpha1/zz_generated.deepcopy.go
  test/e2e/manifests/gitops-operator/argoproj.io_applicationsets.yaml
  test/e2e/manifests/paas-context/capability-applicationsets/appset-argocd.yaml
  test/e2e/manifests/paas-context/capability-applicationsets/appset-cap5as.yaml
  test/e2e/manifests/paas-context/capability-applicationsets/appset-grafana.yaml
  test/e2e/manifests/paas-context/capability-applicationsets/appset-sso.yaml
  test/e2e/manifests/paas-context/capability-applicationsets/appset-tekton.yaml
Labels: enhancement

#524 docs: Removal of all docs related to ArgoCD as a fixed capability.
  docs/development-guide/40_e2e-tests.md
  docs/development-guide/50_notes.md
  docs/development-guide/60_writing-documentation.md
  docs/development-guide/e2e-test-details.md
  docs/overview/core_concepts/authorization.md
  docs/overview/core_concepts/capabilities.md
  docs/overview/core_concepts/index.md
  docs/overview/core_concepts/integrations.md
  docs/overview/core_concepts/paas.md
  docs/overview/core_concepts/sshsecrets.md
  docs/overview/glossary.md
  docs/overview/index.md
  docs/user-guide/02_capabilities.md
  docs/user-guide/03_common_usecases.md
  test/README.md
  test/e2e/manifests/gitops-operator/README.md
Labels: documentation

#525 chore(crypttool): remove crypttool in favor of opr-paas-crypttool repo
  .github/workflows/build-and-release-binaries.yml
  .goreleaser.yaml
  .testcoverage.yaml
  cmd/crypttool/check_paas.go
  cmd/crypttool/decrypt.go
  cmd/crypttool/encrypt.go
  cmd/crypttool/generate.go
  cmd/crypttool/main.go
  cmd/crypttool/main_test.go
  cmd/crypttool/paas_file.go
  cmd/crypttool/paas_file_test.go
  cmd/crypttool/reencrypt.go
  cmd/crypttool/testdata/brokenPaas.yml
  cmd/crypttool/testdata/emptyPaas.json
  cmd/crypttool/testdata/emptyPaas.yml
  cmd/crypttool/testdata/invalidFormat.toml
  cmd/crypttool/testdata/minimalPaas.json
  cmd/crypttool/testdata/minimalPaas.yml
  cmd/crypttool/testdata/unsupportedFieldsPaas.yml
  cmd/webservice/check_paas.go
  cmd/webservice/check_paas_test.go
  cmd/webservice/main.go
  cmd/webservice/main_test.go
  go.mod
  go.sum
  internal/controller/rsa_controller.go
  internal/controller/suite_test.go
  internal/crypt/crypt.go
  internal/crypt/crypt_test.go
  internal/crypt/main.go
  internal/crypt/private_keys.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  internal/webhook/v1alpha1/utils_webhook.go
  internal/webhook/v1alpha1/validated_secrets.go
  internal/webhook/v1alpha1/validated_secrets_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
  test/e2e/sshsecrets_test.go
Labels: chore, ci

#515 chore(style): enable staticcheck linter
  .golangci.yaml
  api/v1alpha1/paas_types_test.go
  api/v1alpha1/paasns_types_test.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/namespaces.go
  internal/controller/paasnamespaces.go
  internal/controller/rolebindings_controller.go
  internal/templating/main_test.go
  internal/templating/yaml_to_test.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
Labels: chore

#527 chore: enabling revive/use-errors-new
  .golangci.yaml
  api/v1alpha1/paasns_types.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasns_controller.go
  internal/validate/main.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  internal/webhook/v1alpha1/validated_secrets_test.go
Labels: chore

#526 chore: enabling revive/indent-error-flow
  .golangci.yaml
  .testcoverage.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/validations.go
  cmd/webservice/main.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/namespaces.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/rsa_controller.go
  internal/controller/secret_controller.go
  internal/fields/elements.go
  internal/fields/entries.go
  internal/groups/groups.go
Labels: chore

#528 chore: enabling revive/exported
  .golangci.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasns_types.go
  api/v1alpha1/validations.go
  cmd/webservice/config.go
  cmd/webservice/data.go
  cmd/webservice/main.go
  cmd/webservice/main_test.go
  internal/config/watcher.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/groups_test.go
  internal/controller/ldap_groups.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/secret_controller.go
  internal/controller/secret_controller_test.go
  internal/fields/elements.go
  internal/fields/entries.go
  internal/groups/groups.go
  internal/logging/main.go
  internal/quota/quota.go
  internal/quota/quota_test.go
  internal/quota/quotalists.go
  internal/quota/quotalists_test.go
  internal/quota/quotas.go
  internal/quota/quotas_test.go
  internal/templating/main.go
  internal/templating/yaml_to.go
  internal/utils/notifier.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  internal/version/main.go
  internal/webhook/v1alpha1/paas_webhook.go
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
Labels: chore

#530 chore: Fixing revive/exported issues for v1alphav2
  api/v1alpha2/paas_types.go
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
Labels: chore

#538 chore(docs): update docs to reflect removal of crypttool
  docs/administrators-guide/sshSecrets.md
  docs/overview/core_concepts/sshsecrets.md
  docs/overview/glossary.md
  docs/user-guide/02_ssh-secrets.md
Labels: documentation, chore

#540 fix: namespace name validation
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_ginkgo_test.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
Labels: bug, documentation

#537 feat: removing paasns reconciler
  .golangci.yaml
  .testcoverage.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasns_types.go
  api/v1alpha2/paas_conversion_test.go
  api/v1alpha2/paas_types.go
  cmd/manager/main.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/clusterrolebindings.go
  internal/controller/main.go
  internal/controller/namespace_def.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/rsa_controller.go
  internal/controller/secret_controller.go
  internal/controller/secret_controller_test.go
  internal/paasresource/main.go
  internal/templating/yaml_to_test.go
  internal/utils/utils_test.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/paasconfig_webhook_test.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  internal/webhook/v1alpha1/utils_webhook.go
  internal/webhook/v1alpha1/validated_secrets.go
  internal/webhook/v1alpha1/webhook_suite_test.go
  internal/webhook/v1alpha2/paas_webhook_test.go
  test/e2e/capability-tekton_test.go
  test/e2e/capability_argocd_test.go
  test/e2e/paas_conversion_test.go
  test/e2e/paasns_test.go
  test/e2e/sshsecrets_test.go
  test/e2e/util.go
Labels: enhancement

#547 ci: bringing improving coverage for internal/controller/clusterrolebindings
  .testcoverage.yaml
  internal/controller/clusterrolebindings.go
  internal/controller/clusterrolebindings_test.go
  internal/controller/paas_controller.go
Labels: ci
