Repository belastingdienst/opr-paas, pull requests merged in 2025-07, with the labels that each got.

#657 chore: Update patch Go version
  go.mod
Labels: chore

#662 ci: Updates cert-manager and operator-sdk
  Makefile
Labels: ci

#668 fix: go-template docs issues
  docs/administrators-guide/go-templating.md
Labels: bug, documentation

#667 docs: administrator conversion of PaasConfig
  docs/administrators-guide/v1alpha1-conversion.md
Labels: documentation

#665 fix(webhook): improve unordered list warning
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
Labels: chore

#675 chore: Adds deprecation warning to v1alpha1 types
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasns_types.go
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paasns.yaml
Labels: chore

#671 docs: converting v1alpha1 to v1alpha2 in docs
  docs/administrators-guide/capabilities.md
  docs/administrators-guide/configuration.md
  docs/administrators-guide/go-templating.md
  docs/administrators-guide/index.md
  docs/administrators-guide/secrets.md
  docs/administrators-guide/validations.md
  docs/development-guide/30_submitting-a-pr.md
  docs/development-guide/31_writing-good-pull-request.md
  docs/development-guide/40_e2e-tests.md
  docs/development-guide/60_writing-documentation.md
  docs/development-guide/e2e-test-details.md
  docs/overview/core_concepts/authorization.md
  docs/overview/core_concepts/capabilities.md
  docs/overview/core_concepts/groupsynclist.md
  docs/overview/core_concepts/integrations.md
  docs/overview/core_concepts/paas.md
  docs/overview/core_concepts/paasns.md
  docs/overview/core_concepts/secrets.md
  docs/overview/core_concepts/sshsecrets.md
  docs/user-guide/01_basic-usage.md
  docs/user-guide/02_application-namespaces.md
  docs/user-guide/02_capabilities.md
  docs/user-guide/02_groups-and-users.md
  docs/user-guide/02_secrets.md
  docs/user-guide/03_common_usecases.md
  internal/controller/groups.go
  manifests/webservice/configmap.yaml
  manifests/webservice/deployment.yaml
  mkdocs.yml
Labels: documentation, minor

#684 feat: disable paas group users in controller
  internal/controller/groups.go
  internal/controller/groups_test.go
Labels: enhancement, minor

#682 docs: feature flag for blocking users
  docs/administrators-guide/feature-flags.md
  docs/administrators-guide/go-templating.md
Labels: documentation

#685 ci: Adds mkdocs kroki plugin
  requirements.txt
Labels: ci, skip-changelog
