Repository belastingdienst/opr-paas, pull requests merged in 2025-03, with the labels that each got.

#406 chore: reduce cyclomatic complexity in manager
  cmd/manager/main.go
Labels: chore

#420 chore: enable some linters
  .golangci.yaml
Labels: chore

#421 chore: enabling revive add-constant linting
  .golangci.yaml
  api/v1alpha1/paas_types_test.go
  api/v1alpha1/paasns_types_test.go
  api/v1alpha1/suite_test.go
  cmd/crypttool/check_paas.go
  cmd/crypttool/decrypt.go
  cmd/crypttool/encrypt.go
  cmd/crypttool/generate.go
  cmd/crypttool/main.go
  cmd/crypttool/main_test.go
  cmd/crypttool/paas_file.go
  cmd/crypttool/paas_file_test.go
  cmd/crypttool/reencrypt.go
  cmd/webservice/check_paas_test.go
  cmd/webservice/config.go
  cmd/webservice/config_test.go
  cmd/webservice/main.go
  cmd/webservice/main_test.go
  internal/controller/argo_app.go
  internal/controller/argo_projects.go
  internal/controller/groups.go
  internal/controller/groups_test.go
  internal/controller/main.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasns_controller.go
  internal/controller/suite_test.go
  internal/crypt/crypt.go
  internal/crypt/crypt_test.go
  internal/crypt/main.go
  internal/crypt/private_keys.go
  internal/logging/main_test.go
  internal/quota/quotalists_test.go
  internal/utils/notifier_test.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  internal/webhook/v1alpha1/validated_secrets_test.go
  test/e2e/capability-tekton_test.go
  test/e2e/capability_argocd_test.go
  test/e2e/groupusers_test.go
  test/e2e/sshsecrets_test.go
Labels: chore

#423 chore: unittests for capabilities
  internal/controller/capabilities_test.go
  internal/controller/suite_test.go
  internal/stubs/argoproj/v1alpha1/applicationset_types.go
  internal/stubs/argoproj/v1alpha1/zz_generated.deepcopy.go
Labels: chore

#424 chore(style): reduce cyclomatic complexity in PaasConfig webhook
  internal/webhook/v1alpha1/paasconfig_webhook.go
Labels: chore

#425 test: e2e tests with appset interface option
  Makefile
  internal/fields/elements.go
  internal/fields/entries.go
  test/e2e/app-project_test.go
  test/e2e/capability-tekton_test.go
  test/e2e/capability_argocd_test.go
  test/e2e/capability_cap5_test.go
  test/e2e/capability_sso_test.go
  test/e2e/util.go
Labels: test

#427 chore(lint): enable (and fix) redundant-import-alias linter rule
  .golangci.yaml
  cmd/webservice/check_paas_test.go
  internal/quota/quotalists.go
  internal/stubs/argoproj-labs/v1beta1/scheme.go
  internal/stubs/argoproj/v1alpha1/scheme.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
  test/e2e/paasconfig_test.go
  test/e2e/sshsecrets_test.go
Labels: chore

#426 test: flakey test on secret_controller
  internal/controller/groups_test.go
  internal/controller/secret_controller_test.go
  internal/controller/suite_test.go
Labels: test

#428 chore(lint): enable and fix revive receiver-naming linter rule
  .golangci.yaml
  api/v1alpha1/paasns_types.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasns_controller.go
Labels: chore

#429 chore(lint): enable redefines-builtin-id revive rule and fix issues
  .golangci.yaml
  api/v1alpha1/paas_types.go
  internal/controller/clusterrolebindings.go
  internal/quota/quotalists_test.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
Labels: chore

#432 chore(lint): enable max-control-nesting Revive linter rule and fix
  .golangci.yaml
  internal/controller/paas_controller.go
Labels: chore

#433 chore(lint): enable increment-decrement linter rule and fix
  .golangci.yaml
  cmd/crypttool/check_paas.go
  cmd/crypttool/reencrypt.go
  internal/utils/notifier.go
Labels: chore

#434 chore(lint): enable import-shadowing linter rule and fix issues
  .golangci.yaml
  api/v1alpha1/paas_types.go
  cmd/crypttool/check_paas.go
  cmd/webservice/check_paas.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/ldap_groups.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/logging/main_test.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/validated_secrets.go
Labels: chore

#435 chore(lint): enable lint rule import-alias-naming and fix
  .golangci.yaml
  api/v1alpha1/paas_types.go
  cmd/manager/main.go
  cmd/webservice/main.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/quota/quotalists_test.go
  internal/quota/quotas_test.go
Labels: chore

#436 fix(docs): Updated example ApplicationSet in capability docs
  docs/administrators-guide/configuration.md
  docs/overview/core_concepts/capabilities.md
Labels: bug, documentation

#437 chore: gofumpt
  internal/controller/capabilities_test.go
  internal/controller/secret_controller_test.go
  internal/controller/suite_test.go
  internal/utils/notifier_test.go
  test/e2e/groupquery_test.go
  test/e2e/paasconfig_test.go
Labels: chore

#438 chore: expanding fields module
  internal/fields/elements.go
  internal/fields/entries.go
  internal/fields/entries_test.go
Labels: chore

#422 feat: Adding groups field to Applicationset
  internal/controller/capabilities.go
  internal/controller/capabilities_test.go
  test/e2e/capability_argocd_test.go
Labels: enhancement

#443 chore: revive/var-declaration
  .golangci.yaml
  internal/crypt/private_keys.go
Labels: chore

#395 chore: local-e2e added to Makefile
  Makefile
  examples/resources/_v1alpha1_paasconfig.yaml
Labels: chore

#442 chore: disabling revive/flag-parameter
  .golangci.yaml
Labels: chore

#445 chore: adding check-coverage (manual for now)
  .testcoverage.yaml
  Makefile
Labels: chore

#431 chore(style): reduce cyclomatic complexity in controller code
  internal/controller/cluster_wide_quota.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
Labels: chore

#448 chore: enable [empty-lines] revive linting rule
  .golangci.yaml
Labels: chore

#446 chore: coverage of internal/fields
  internal/controller/capabilities_test.go
  internal/fields/elements.go
  internal/fields/elements_test.go
  internal/fields/entries.go
  internal/fields/entries_test.go
  test/e2e/capability_argocd_test.go
Labels: chore

#451 chore: enable [dot-imports] revive linting rule
  .golangci.yaml
Labels: chore

#452 chore: enable [context-as-argument] revive linting rule
  .golangci.yaml
  internal/controller/clusterrolebindings.go
  internal/controller/namespaces.go
  internal/controller/paasnamespaces.go
Labels: chore

#447 chore(lint): remove redundant if statements
  .golangci.yaml
  internal/controller/paasconfig_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/secret_controller.go
Labels: chore

#450 chore: enable [early-return] revive linting rule
  .golangci.yaml
  internal/controller/paas_controller.go
  internal/fields/entries.go
Labels: chore

#457 chore: Making suffix in managed-by-label value configurable
  api/v1alpha1/paasconfig_types.go
  internal/controller/namespaces.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/main_test.go
Labels: chore

#460 ci: Adding Paas controller unittest
  internal/controller/argo_app.go
  internal/controller/paas_controller_test.go
  internal/controller/suite_test.go
Labels: ci

#461 chore: disable argo
  api/v1alpha1/paasconfig_types.go
  internal/controller/argo_projects.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/suite_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/main_test.go
Labels: chore

#459 fix(docs): Update casing for PaasNS
  docs/overview/core_concepts/authorization.md
  docs/overview/core_concepts/paasns.md
  docs/overview/core_concepts/sshsecrets.md
  docs/user-guide/02_application-namespaces.md
Labels: bug, documentation

#472 chore: ci on unittest coverage
  .github/workflows/ci-run-on-pr.yaml
  .testcoverage.yaml
  Makefile
Labels: chore, ci

#474 fix: Rollback providing groups as interface into appset generator fields
  .github/workflows/ci-run-on-pr.yaml
  .testcoverage.yaml
  internal/controller/capabilities.go
  internal/controller/capabilities_test.go
  test/e2e/capability_argocd_test.go
Labels: bug, ci

#477 feat: templating module
  go.mod
  internal/templating/main.go
  internal/templating/main_test.go
  internal/templating/yaml_to.go
  internal/templating/yaml_to_test.go
Labels: enhancement

#476 chore: enable function-length linting rule
  .golangci.yaml
  cmd/crypttool/paas_file_test.go
  cmd/crypttool/reencrypt.go
  cmd/webservice/config_test.go
  cmd/webservice/main_test.go
  test/e2e/capability_argocd_test.go
Labels: chore

#490 ci: Updates golangci-lint to v6.5.2
  .github/workflows/ci-run-on-pr.yaml
Labels: ci

#495 chore: paasconfig webhook to fail when required and/or default is set together with template
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/paasconfig_webhook_test.go
Labels: chore

#494 chore: Fixes #492 - Store entire PaasConfig for go-template feature
  internal/config/paas_config_store.go
  internal/config/paas_config_store_test.go
  internal/controller/argo_app.go
  internal/controller/argo_projects.go
  internal/controller/argocd.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/rsa_controller.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/utils_webhook.go
Labels: chore

#493 feat: Adds sprig to use more templating in gotemplate
  go.mod
  go.sum
  internal/templating/main.go
Labels: enhancement

#496 test: improve test coverage
  .golangci.yaml
  .testcoverage.yaml
  internal/groups/groups_test.go
  internal/logging/main_test.go
  internal/validate/main_test.go
Labels: test

#384 feat: Removes ArgoCD capability code
  .testcoverage.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasconfig_types.go
  internal/controller/argo_app.go
  internal/controller/argo_projects.go
  internal/controller/argocd.go
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  manifests/rbac/role.yaml
  test/e2e/app-project_test.go
  test/e2e/capability_argocd_test.go
  test/e2e/manifests/gitops-operator/argoproj.io_applications.yaml
  test/e2e/manifests/gitops-operator/argoproj.io_appprojects.yaml
  test/e2e/manifests/gitops-operator/argoproj.io_argocds.yaml
  test/e2e/manifests/gitops-operator/kustomization.yaml
Labels: enhancement

#498 feat: sprout templating
  docs/administrators-guide/capabilities.md
  go.mod
  go.sum
  internal/templating/main.go
Labels: documentation, enhancement
