Repository belastingdienst/opr-paas, pull requests merged in 2025-08, with the labels that each got.

#690 docs(user-guide): Fix rendering of change lists
  docs/user-guide/v1alpha1-conversion.md
Labels: documentation

#694 ci: Fixes Kroki docs deploy by using Post method
  mkdocs.yml
Labels: ci

#697 docs: Update user-guide for PaasNS
  docs/user-guide/02_application-namespaces.md
Labels: documentation

#696 feat: Implements plugin generator for ArgoCD
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  api/v1alpha2/paas_types.go
  api/v1alpha2/paasconfig_types.go
  cmd/manager/main.go
  internal/argocd-plugin-generator/fields/elements.go
  internal/argocd-plugin-generator/fields/elements_test.go
  internal/argocd-plugin-generator/fields/entries.go
  internal/argocd-plugin-generator/fields/entries_test.go
  internal/argocd-plugin-generator/generator_server.go
  internal/argocd-plugin-generator/generator_server_test.go
  internal/argocd-plugin-generator/handler.go
  internal/argocd-plugin-generator/handler_test.go
  internal/argocd-plugin-generator/plugin_generator.go
  internal/argocd-plugin-generator/plugin_generator_test.go
  internal/argocd-plugin-generator/service.go
  internal/argocd-plugin-generator/service_test.go
  internal/argocd-plugin-generator/suite_test.go
  internal/controller/capabilities.go
  internal/controller/capabilities_test.go
  internal/controller/paas_controller_test.go
  internal/templating/yaml_to.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/util.go
Labels: enhancement, minor

#703 docs: ArgoCD plugin generator
  docs/overview/core_concepts/integrations.md
Labels: documentation, minor

#704 feat: Optional list generator implementation
  api/v1alpha1/paasconfig_types.go
  api/v1alpha2/paasconfig_types.go
  internal/controller/capabilities.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
Labels: enhancement, minor

#707 ci: Update golangci-lint
  .github/workflows/ci-run-on-pr.yaml
  Makefile
Labels: ci

#705 chore: Migrate to Golang 1.25
  .github/workflows/ci-run-on-pr.yaml
  Dockerfile
  Dockerfile.webservice
  go.mod
Labels: chore, ci

#708 docs: Update link to Sprout docs
  docs/administrators-guide/go-templating.md
Labels: documentation

#716 ci: Use ubuntu-latest
  .github/workflows/ci-run-on-pr.yaml
Labels: ci

#718 test: Migrating e2e from v1alpha1 to v1alpha2
  test/e2e/capability-tekton_test.go
  test/e2e/capability_argocd_test.go
  test/e2e/capability_cap5_test.go
  test/e2e/capability_sso_test.go
  test/e2e/clusterresourcequota_test.go
  test/e2e/groupquery_test.go
  test/e2e/groupusers_test.go
  test/e2e/paas.go
  test/e2e/paas_conversion_test.go
  test/e2e/sshsecrets_test.go
  test/e2e/steps.go
Labels: test

#722 refactor: Prevent no-op updates of clusterquotas on addTo
  internal/controller/cluster_wide_quota.go
Labels: refactor

#727 docs: Small fix on v1alpha2 conversion user docs
  docs/user-guide/99_v1alpha1-conversion.md
Labels: documentation
