Repository belastingdienst/opr-paas, pull requests merged in 2025-09, with the labels that each got.

#728 docs: allowedQuotas
  docs/administrators-guide/validations.md
Labels: documentation

#730 hotfix: fail and log error when PaasConfig is not yet initialized
  internal/argocd-plugin-generator/generator_server.go
  internal/argocd-plugin-generator/handler.go
  internal/argocd-plugin-generator/plugin_generator.go
  internal/argocd-plugin-generator/service.go
  internal/config/informer.go
  internal/config/paas_config_store.go
  internal/config/paas_config_store_test.go
  internal/webhook/v1alpha2/paas_webhook.go
  internal/webhook/v1alpha2/paasns_webhook.go
Labels: bug

#731 docs: Component Logging docs
  cmd/manager/main.go
  docs/administrators-guide/debugging.md
  internal/argocd-plugin-generator/generator_server.go
  internal/argocd-plugin-generator/handler.go
  internal/argocd-plugin-generator/plugin_generator.go
  internal/argocd-plugin-generator/service.go
  internal/config/informer.go
  internal/config/paas_config_store.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/namespace_def.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/rsa_controller.go
  internal/controller/secret_controller.go
  internal/logging/components.go
  internal/logging/components_test.go
  internal/logging/main.go
  internal/logging/main_test.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/utils_webhook.go
  internal/webhook/v1alpha2/paas_webhook.go
  internal/webhook/v1alpha2/paasconfig_webhook.go
  internal/webhook/v1alpha2/paasns_webhook.go
Labels: documentation

#750 chore: replace gopkg.in/yaml.v3 by github.com/goccy/go-yaml
  go.mod
  go.sum
  internal/templating/yaml_to.go
Labels: chore

#753 fix: #744
  api/v1alpha2/paasconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  docs/administrators-guide/v1alpha1-conversion.md
  docs/overview/core_concepts/capabilities.md
  examples/resources/_v1alpha2_paasconfig.yaml
Labels: bug, documentation

#765 refactor: Simplify mergeSecrets code
  internal/controller/main.go
  internal/controller/main_test.go
  internal/controller/namespace_def.go
Labels: refactor
