Repository belastingdienst/opr-paas, pull requests merged in 2025-01, with the labels that each got.

#236 chore: Minor improvements to issue templates
  .github/ISSUE_TEMPLATE/01_BUG_REPORT.md
  .github/ISSUE_TEMPLATE/03_CODEBASE_IMPROVEMENT.md
Labels: documentation, chore, ci

#227 fix: Auto-label regex improvement
  .github/release-drafter.yml
Labels: bug, ci

#229 revert: Clear api docs as they are auto generated
  docs/development-guide/00_api.md
Labels: documentation, revert

#225 revert: Simplify setting successfull condition in Paas controller
  internal/controller/paas_controller.go
Labels: revert

#224 chore: Simplify paasconfig predicate
  internal/controller/paasconfig_controller.go
Labels: chore

#217 docs: expand navigation by default
  mkdocs.yml
Labels: documentation

#228 chore: Removes redundant finalizers
  internal/controller/argo_app.go
  internal/controller/argo_projects.go
  internal/controller/paas_controller.go
Labels: chore

#238 ci: Speed up docker builds
  Dockerfile
  Dockerfile.webservice
Labels: ci

#239 spike: test ospo code scanner workflow
  .github/workflows/scan.yml
Labels: ci

#240 revert: "spike: test ospo code scanner workflow (#239)"
  .github/workflows/scan.yml
Labels: ci

#215 chore: PaasConfig fields omitempty
  api/v1alpha1/paasconfig_types.go
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/main_test.go
Labels: chore

#230 chore: Kubebuilder as the de facto way of writing api's
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasns_types.go
  docs/administrators-guide/capabilities.md
  docs/administrators-guide/configuration.md
  examples/resources/_v1alpha1_paasconfig.yaml
  internal/controller/argo_projects.go
  manifests/crds/cpet.belastingdienst.nl_paas.yaml
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  manifests/crds/cpet.belastingdienst.nl_paasns.yaml
  test/e2e/main_test.go
  test/manifests/config/paas_config.yml
Labels: documentation, chore

#221 docs: Adding architectural images
  docs/overview/core_concepts/bootstrap.png
  docs/overview/core_concepts/integrations.md
  docs/overview/core_concepts/paasns.md
  docs/overview/core_concepts/paasns.png
Labels: documentation

#222 chore: Renaming Whitelist to GroupSyncList
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/administrators-guide/configuration.md
  docs/development-guide/e2e-test-details.md
  docs/overview/core_concepts/authorization.md
  docs/overview/core_concepts/groupsynclist.md
  examples/resources/_v1alpha1_paas.yaml
  examples/resources/_v1alpha1_paasconfig.yaml
  internal/controller/ldap_groups.go
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/groupquery_test.go
  test/e2e/groupusers_test.go
  test/e2e/main_test.go
  test/e2e/manifests/paas-context/groupsynclist/kustomization.yaml
  test/e2e/manifests/paas-context/groupsynclist/ns-gslns.yaml
  test/e2e/manifests/paas-context/kustomization.yaml
Labels: documentation, chore

#244 ci(docs): auto publish versioned docs
  .github/workflows/build-and-publish-docs.yaml
  mkdocs.yml
  mkdocs_overrides/main.html
  requirements.txt
Labels: ci

#245 fix(ci): correct docs workflow
  .github/workflows/build-and-publish-docs.yaml
Labels: ci

#247 ci: Run pr workflow more specifically
  .github/workflows/ci-run-on-pr.yaml
Labels: ci

#249 fix: Ci not triggered after #247
  .github/workflows/ci-run-on-pr.yaml
Labels: ci, skip-changelog

#251 fix: Auto-label regex
  .github/release-drafter.yml
Labels: ci, skip-changelog

#250 docs: Update according to PaasConfig crd
  README.md
  docs/administrators-guide/cluster-wide-quotas/basic-usage.md
  docs/administrators-guide/install.md
  docs/overview/core_concepts/authorization.md
  docs/overview/core_concepts/capabilities.md
  docs/overview/glossary.md
Labels: documentation

#255 chore: Let Dependabot manage more packages
  .github/dependabot.yml
Labels: chore, ci

#256 test: Cleanup main_test.go
  internal/controller/main_test.go
Labels: test

#254 ci: add license compatibility check
  .github/workflows/build-and-release-sbom.yml
  .github/workflows/ci-check-licenses.yml
Labels: ci

#271 ci: Fix run ci-build on correct changes
  .github/workflows/ci-run-on-pr.yaml
Labels: ci

#274 feat: Configurable GroupSyncList key
  api/v1alpha1/paasconfig_types.go
  docs/overview/core_concepts/groupsynclist.md
  internal/controller/ldap_groups.go
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/main_test.go
Labels: documentation, enhancement

#272 fix: Remove old groups on Paas group spec update
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/paas_controller.go
  test/e2e/groupquery_test.go
  test/e2e/groupusers_test.go
Labels: bug

#275 ci: Fix Mike deploy
  .github/workflows/build-and-publish-docs.yaml
Labels: ci

#278 fix: correct conversion int64 float64
  Makefile
  api/v1alpha1/paasconfig_types.go
  docs/administrators-guide/capabilities.md
  docs/administrators-guide/configuration.md
  examples/resources/_v1alpha1_paasconfig.yaml
  internal/quota/quotalists.go
  internal/quota/quotalists_test.go
  internal/quota/quotas.go
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/main_test.go
Labels: bug, documentation, minor

#281 chore: Enhancing crd validation
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasns_types.go
  manifests/crds/cpet.belastingdienst.nl_paas.yaml
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  manifests/crds/cpet.belastingdienst.nl_paasns.yaml
  test/e2e/paasns_test.go
Labels: chore

#282 chore: Removes useless log statement from e2e
  test/e2e/groupquery_test.go
Labels: chore, skip-changelog

#279 feat: decryptsecret from k8s
  .github/workflows/ci-run-on-pr.yaml
  Makefile
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/crypttool/check_paas.go
  cmd/crypttool/reencrypt.go
  cmd/webservice/main.go
  internal/controller/main.go
  internal/controller/paasconfig_controller.go
  internal/controller/rsa_controller.go
  internal/controller/secret_controller.go
  internal/crypt/crypt.go
  internal/crypt/main.go
  internal/crypt/private_keys.go
  manifests/crds/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/fixtures/crypt/priv/0
  test/e2e/fixtures/crypt/priv/1
  test/e2e/main_test.go
  test/e2e/sshsecrets_test.go
Labels: enhancement, ci

#288 ci: Make make run-operator idempotent
  Makefile
Labels: ci

#287 docs: Update PaasConfig docs and example
  docs/administrators-guide/configuration.md
  examples/resources/_v1alpha1_paasconfig.yaml
Labels: documentation

#294 docs: Examples on how this project is being used and the value it brings
  docs/administrators-guide/sshSecrets.md
  docs/overview/core_concepts/index.md
  docs/overview/core_concepts/paasns.md
  docs/overview/index.md
  docs/user-guide/01_basic-usage.md
  docs/user-guide/02_adding-extras.md
  docs/user-guide/02_application-namespaces.md
  docs/user-guide/02_capabilities.md
  docs/user-guide/02_groups-and-users.md
  docs/user-guide/02_ssh-secrets.md
  docs/user-guide/03_common_usecases.md
  docs/user-guide/use-case1.png
  manifests/default/kustomization.yaml
  manifests/webservice/configmap.yaml
  manifests/webservice/deployment.yaml
  manifests/webservice/kustomization.yaml
  manifests/webservice/route.yaml
  manifests/webservice/service.yaml
Labels: documentation

#298 ci: Only run e2e against deployed image
  .github/workflows/ci-run-on-pr.yaml
  Makefile
  Procfile
Labels: ci

#297 fix: Create rolebindings when groupKey is different then its query value
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  internal/controller/paas_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/rolebindings_controller.go
  test/e2e/groupquery_test.go
Labels: bug

#296 chore: Updates example Paas
  examples/resources/_v1alpha1_paas.yaml
Labels: chore

#295 refactor: Use deepequal to compare rolebinding subjects
  internal/controller/rolebindings_controller.go
Labels: refactor

#286 feat: webservice secrets refresh
  cmd/webservice/check_paas.go
  cmd/webservice/main.go
  cmd/webservice/main_test.go
  go.mod
  internal/utils/notifier.go
  internal/utils/notifier_test.go
Labels: enhancement

#237 feat: Scaffold the project for Webhook setup
  .gitignore
  Makefile
  PROJECT
  api/v1alpha1/paas_webhook.go
  api/v1alpha1/paas_webhook_test.go
  api/v1alpha1/webhook_suite_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  go.mod
  manifests/certmanager/certificate.yaml
  manifests/certmanager/kustomization.yaml
  manifests/certmanager/kustomizeconfig.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paasns.yaml
  manifests/crd/kustomization.yaml
  manifests/crd/kustomizeconfig.yaml
  manifests/crds/kustomization.yaml
  manifests/default/kustomization.yaml
  manifests/default/manager_webhook_patch.yaml
  manifests/manager/opr-paas-deployment.yaml
  manifests/webhook/kustomization.yaml
  manifests/webhook/kustomizeconfig.yaml
  manifests/webhook/manifests.yaml
  manifests/webhook/service.yaml
Labels: enhancement, ci

#305 test(controller): setup envTest and define initial controller scenario
  api/v1alpha1/webhook_suite_test.go
  go.mod
  internal/controller/secret_controller_test.go
  internal/controller/suite_test.go
  internal/utils/notifier_test.go
Labels: test

#307 ci: Use sha and permission in release workflows
  .github/workflows/draft-release-on-push.yml
  .github/workflows/update-trivy-cache.yml
Labels: ci

#316 fix: Reload webservice secret repeatedly
  cmd/webservice/main.go
  internal/utils/notifier.go
  internal/utils/notifier_test.go
Labels: bug

#318 ci: Fix update Trivy cache workflow
  .github/workflows/update-trivy-cache.yml
Labels: ci

#319 fix(ci): oras install for workflow
  .github/workflows/update-trivy-cache.yml
Labels: bug, ci

#321 ci: fix setup-oras action sha
  .github/workflows/update-trivy-cache.yml
Labels: ci

#317 fix: Set correct groupNames in ArgoCD after redesigning the groupNames
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  internal/controller/argocd.go
Labels: bug

#322 feat: add configurable CORS settings, CSP and nosniff
  cmd/webservice/check_paas_test.go
  cmd/webservice/config.go
  cmd/webservice/config_test.go
  cmd/webservice/main.go
  cmd/webservice/main_test.go
Labels: enhancement

#323 fix: Updates to a Paas reconciles appSetCaps
  internal/controller/capabilities.go
  internal/controller/paas_controller.go
  internal/controller/paasns_controller.go
Labels: bug

#324 chore: add example CORS origin to deployment manifest
  docs/administrators-guide/sshSecrets.md
  manifests/webservice/deployment.yaml
Labels: documentation, chore

#325 docs: Adding use-case1.png with new Paas logo
  docs/user-guide/use-case1.png
Labels: documentation

#326 docs: add branding page with logos to docs
  docs/about/branding/index.md
  docs/about/branding/paas-logo-v1-120x80px.png
  docs/about/branding/paas-logo-v1-149x100px.png
  docs/about/branding/paas-logo-v1-16x16px.png
  docs/about/branding/paas-logo-v1-180x180px.png
  docs/about/branding/paas-logo-v1-32x32px.png
  docs/about/branding/paas-logo-v1-400x400px.png
  docs/about/branding/paas-logo-v1-500x335px.png
  mkdocs.yml
Labels: documentation
