Repository belastingdienst/opr-paas, pull requests merged in 2025-02, with the labels that each got.

#329 chore: add SVG src file for logo
  .gitignore
  docs/about/branding/paas-logo-v1.svg
Labels: documentation, chore

#337 refactor: move active PaasConfig cache to separate package
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  internal/config/main.go
  internal/controller/argo_app.go
  internal/controller/argo_projects.go
  internal/controller/argocd.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/main.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/rsa_controller.go
  internal/controller/suite_test.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
Labels: refactor

#338 fix(docs): update command to start operator in e2e test doc
  docs/development-guide/40_e2e-tests.md
Labels: bug, documentation

#340 chore: Updates gomod by removing replace block as that is no longer needed
  go.mod
  go.sum
Labels: chore

#332 feat(paas_webhook): add capability validation in admission webhook
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  test/e2e/capability-cap6_test.go
Labels: enhancement

#342 chore: add ginkgolinter to golangci-lint config and fix linter issue
  .golangci.yaml
  internal/controller/secret_controller_test.go
Labels: chore

#339 chore: implementing internal/logging
  cmd/manager/main.go
  internal/controller/argo_app.go
  internal/controller/argo_projects.go
  internal/controller/argocd.go
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/ldap_groups.go
  internal/controller/main.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/paasnamespaces.go
  internal/controller/paasns_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/rsa_controller.go
  internal/controller/secret_controller.go
  internal/logging/main.go
  internal/logging/main_test.go
Labels: chore

#347 fix: resources requests.cpu for tekton and argocd capability in Paas …
  examples/resources/_v1alpha1_paas.yaml
Labels: bug

#346 ci: Cancel in-progress pr-title-check.yml
  .github/workflows/pr-title-check.yml
Labels: ci

#348 ci: install kind using Go & create a cluster during CI
  .github/workflows/ci-run-on-pr.yaml
Labels: ci

#343 chore: error messages should be without caps
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
Labels: chore

#357 ci: update pr-title-check.yml
  .github/workflows/pr-title-check.yml
Labels: ci

#341 feat(paas_webhook): add secrets validation
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
  test/e2e/paasconfig_test.go
Labels: enhancement

#363 chore: Refining crypt so that it has a nicer interface for unittests
  cmd/webservice/check_paas_test.go
  cmd/webservice/main_test.go
  internal/crypt/crypt.go
  internal/crypt/crypt_test.go
  internal/crypt/main.go
Labels: chore

#364 feat: Paas webhook, group validation
  examples/resources/_v1alpha1_paas.yaml
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
Labels: enhancement

#327 feat: paasns webhook
  .golangci.yaml
  cmd/manager/main.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  internal/webhook/v1alpha1/utils_webhook.go
  internal/webhook/v1alpha1/validated_secrets.go
  internal/webhook/v1alpha1/validated_secrets_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
  manifests/manager/kustomization.yaml
  manifests/webhook/manifests.yaml
  test/e2e/paasns_test.go
Labels: enhancement

#367 chore: Re-enabling paasns delete check previously disabled by paasns webhook pr
  test/e2e/paasns_test.go
Labels: chore

#377 hotfix: do not manage users for ldap managed groups
  internal/controller/groups.go
  internal/controller/groups_test.go
Labels: bug

#378 hotfix: managing users in groups should not happen to ldap managed groups
  internal/controller/groups.go
  internal/controller/groups_test.go
Labels: bug

#379 chore: Update makefile deps
  Makefile
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  manifests/crd/bases/cpet.belastingdienst.nl_paasns.yaml
  manifests/rbac/role.yaml
Labels: chore, minor

#361 feat(paas_webhook): validate custom fields
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
Labels: enhancement

#380 feat: Validate namespaces in crd
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_ginkgo_test.go
  api/v1alpha1/suite_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
Labels: enhancement

#382 feat(paas_webhook): warn if quota requests higher than limits
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
Labels: enhancement

#381 feat: Implementing PaasNs ValidateUpdate webhook
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
Labels: enhancement

#386 test(webhook): refactor secret usage in Paas webhook
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
Labels: test

#389 feat: validate paas.spec.groups keys
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  test/e2e/groupquery_test.go
Labels: enhancement

#356 ci(tests): add more tests for PaasConfig validating webhook
  .gitignore
  api/v1alpha1/paasconfig_types.go
  examples/resources/_v1alpha1_paasconfig.yaml
  internal/config/main.go
  internal/config/main_test.go
  internal/validate/main.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/paasconfig_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/capability-cap6_test.go
  test/e2e/groupquery_test.go
  test/e2e/main_test.go
  test/e2e/paasconfig_test.go
Labels: ci

#400 chore(lint): fix unexported-naming issues
  test/e2e/capability-tekton_test.go
Labels: chore

#402 chore: fix unchecked type assertion issue
  api/v1alpha1/paasconfig_types.go
Labels: chore

#403 chore(style): fix superfluous else linter issue
  cmd/manager/main.go
  internal/crypt/crypt.go
  internal/crypt/private_keys.go
Labels: chore, style

#401 chore: eliminate bare returns
  .golangci.yaml
  api/v1alpha1/paas_types.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/namespaces.go
  internal/controller/paasns_controller.go
  internal/webhook/v1alpha1/paas_webhook.go
Labels: chore, style

#409 feat: configurable groupname verification
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs/administrators-guide/configuration.md
  docs/administrators-guide/validations.md
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/paasconfig_webhook_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
Labels: bug, documentation, enhancement

#407 fix(PaasConfigWebhook): do not check Min > Def error situation if Clusterwide
  internal/webhook/v1alpha1/paasconfig_webhook.go
  internal/webhook/v1alpha1/paasconfig_webhook_test.go
  internal/webhook/v1alpha1/webhook_suite_test.go
Labels: bug

#410 chore: revive/var-naming
  .golangci.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasns_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/crypttool/check_paas.go
  cmd/crypttool/reencrypt.go
  cmd/webservice/check_paas.go
  cmd/webservice/check_paas_test.go
  cmd/webservice/data.go
  cmd/webservice/main_test.go
  internal/controller/groups.go
  internal/controller/paasnamespaces.go
  internal/controller/secret_controller.go
  internal/controller/secret_controller_test.go
  internal/groups/groups.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paas_webhook_test.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/paasns_webhook_test.go
  internal/webhook/v1alpha1/validated_secrets.go
  internal/webhook/v1alpha1/validated_secrets_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasns.yaml
  test/e2e/capability-tekton_test.go
  test/e2e/capability_argocd_test.go
  test/e2e/capability_cap5_test.go
  test/e2e/capability_sso_test.go
  test/e2e/sshsecrets_test.go
Labels: chore

#411 feat: AppSet list generator fields as interface
  api/v1alpha1/paas_types.go
  api/v1alpha1/paas_types_test.go
  internal/controller/argo_app.go
  internal/controller/capabilities.go
  internal/fields/elements.go
  internal/fields/entries.go
Labels: enhancement

#404 chore(style): remove unsupported inline struct tag
  .golangci.yaml
  api/v1alpha1/paas_types.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha1/paasns_types.go
  internal/stubs/argoproj-labs/v1beta1/gitops.go
  internal/stubs/argoproj/v1alpha1/app_project_types.go
  internal/stubs/argoproj/v1alpha1/application.go
  internal/stubs/argoproj/v1alpha1/applicationset_types.go
Labels: chore

#413 hotfix: Fixing #412
  cmd/manager/main.go
  internal/config/paas_config_store.go
  internal/config/paas_config_store_test.go
  internal/config/watcher.go
  internal/controller/paasconfig_controller.go
  internal/logging/main.go
Labels: bug
