Repository belastingdienst/opr-paas, pull requests merged in 2025-06, with the labels that each got.

#607 chore: merge main to v1alpha2
  docs/overview/core_concepts/authorization.md
  go.mod
  go.sum
Labels: documentation, chore

#613 chore: remove obsolete Status block
  api/v1alpha2/paasns_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasns.yaml
Labels: chore

#615 fix: failing v1alpha2 tests
  api/v1alpha1/paas_conversion.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings_test.go
  internal/controller/namespace_def.go
  internal/controller/namespaces.go
  internal/quota/quota.go
  test/e2e/capability_argocd_test.go
  test/e2e/paas_conversion_test.go
Labels: bug

#618 fix: ArgoCD obsolete fields during conversion
  api/v1alpha1/paas_conversion.go
  api/v1alpha1/paas_conversion_test.go
  test/e2e/paas_conversion_test.go
Labels: bug

#619 chore: cleanup
  api/v1alpha1/paasns_conversion_test.go
Labels: chore

#621 chore: Improved label selector for secret management
  internal/controller/secret_controller.go
Labels: chore

#634 test: Adding unittests for label management
  internal/controller/cluster_quotas_test.go
  internal/controller/groups_test.go
  internal/controller/namespace_test.go
  internal/controller/rolebindings_controller_test.go
Labels: test

#639 feat: go templating requestor
  api/v1alpha2/paas_types.go
  internal/controller/namespaces.go
  internal/controller/namespaces_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paas.yaml
Labels: enhancement

#638 feat: capability go templating
  api/v1alpha2/paasconfig_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  internal/controller/capabilities.go
  internal/controller/capabilities_test.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_quotas_test.go
  internal/controller/groups.go
  internal/controller/groups_test.go
  internal/controller/namespaces.go
  internal/controller/namespaces_test.go
  internal/controller/rolebindings_controller.go
  internal/controller/rolebindings_controller_test.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasconfig.yaml
  test/e2e/main_test.go
Labels: enhancement

#643 chore: Some code quality improvements
  api/v1alpha1/paas_types_test.go
  api/v1alpha1/paasns_types_test.go
  api/v1alpha2/suite_test.go
  cmd/webservice/data.go
  cmd/webservice/main_test.go
  go.mod
  go.sum
  internal/controller/capabilities.go
  internal/controller/cluster_quotas.go
  internal/controller/cluster_wide_quota.go
  internal/controller/clusterrolebindings.go
  internal/controller/groups.go
  internal/controller/main.go
  internal/controller/namespaces.go
  internal/controller/paas_controller.go
  internal/controller/paasconfig_controller.go
  internal/controller/rolebindings_controller.go
  internal/controller/secret_controller.go
  internal/controller/suite_test.go
  internal/fields/entries.go
  internal/fields/entries_test.go
  internal/groups/groups.go
  internal/logging/main_test.go
  internal/quota/quotas_test.go
  internal/webhook/v1alpha1/paas_webhook.go
  internal/webhook/v1alpha1/paasns_webhook.go
  internal/webhook/v1alpha1/validated_secrets.go
  internal/webhook/v1alpha2/paas_webhook.go
  internal/webhook/v1alpha2/paasns_webhook.go
  test/e2e/groupquery_test.go
  test/e2e/paasns_test.go
Labels: chore

#651 chore: Fixing linting feedback
  .github/workflows/draft-release-on-push.yml
  CONTRIBUTING.md
  api/v1alpha1/paas_types_test.go
  api/v1alpha1/paasconfig_types.go
  api/v1alpha2/paasconfig_types.go
  docs/administrators-guide/capabilities.md
  docs/administrators-guide/cluster-wide-quotas/benefits.md
  docs/development-guide/00_api.md
  docs/development-guide/31_writing-good-pull-request.md
  docs/development-guide/60_writing-documentation.md
  docs/development-guide/index.md
  docs/development-guide/maintaining.md
  docs/overview/core_concepts/paasns.md
  docs/overview/core_concepts/sshsecrets.md
  docs/overview/glossary.md
  docs/user-guide/02_groups-and-users.md
  docs/user-guide/02_ssh-secrets.md
  internal/controller/paas_controller.go
  internal/controller/paas_controller_test.go
  internal/groups/groups.go
  internal/logging/main.go
  internal/quota/quotas.go
  internal/utils/utils_test.go
  internal/webhook/v1alpha1/paas_webhook.go
  manifests/webservice/deployment.yaml
Labels: documentation, chore, ci

#653 fix: Updates project to allow configuring metrics endpoint
  cmd/manager/main.go
  go.mod
  go.sum
  manifests/rbac/kustomization.yaml
  manifests/rbac/metrics_auth_role.yaml
  manifests/rbac/metrics_auth_role_binding.yaml
  manifests/rbac/metrics_reader_role.yaml
Labels: bug

#652 feat: PaasNs no longer requires spec.paas and implements conversion
  api/v1alpha2/paasns_types.go
  internal/controller/namespace_def.go
  internal/controller/paas_controller.go
  manifests/crd/bases/cpet.belastingdienst.nl_paasns.yaml
  manifests/crd/kustomization.yaml
  manifests/crd/patches/webhook_in_paasns.yaml
Labels: enhancement
